server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: all
      enable:
        idempotence: true

    consumer:
      group-id: orders
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.f_lab.la_planete.core.*
      isolation-level: read_committed

orders:
  events:
    topic:
      name: orders.order-created-event
      fail: orders.orders-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3


logging:
  level:
    org:
      apache:
        kafka: error
        orm:
          jpa:
            JpaTransactionManager: trace
