server.port: 8081

spring:
  application:
    name: foods

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/Desktop/software/h2/h2-datafile/kafka
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true

  kafka:
    producer:
      transaction-id-prefix: foods-tx

    consumer:
      group-id: foods

orders:
  events:
    topic:
      name: orders.order-created-event

foods:
  events:
    topic:
      name: foods.order-created-event
      fail: foods.order-creation-failed-event

  dead-letter-topic:
    name: foods.dead-letter-topic

payments:
  events:
    topic:
      fail: payments.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3

logging:
  level:
    org.hibernate.sql: TRACE
#
#    org.springframework.kafka: TRACE
#    org.apache.kafka: TRACE