server.port: 8081

spring:
  application:
    name: foods

  jpa:
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: foods-tx

    consumer:
      group-id: foods

orders:
  events:
    topic:
      name: orders.order-created-event

foods:
  events:
    topic:
      name: foods.order-created-event
      fail: foods.foods-reservation-fail-event

  dead-letter-topic:
    name: foods.dead-letter-topic

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3

non-retryable-errors:
  - "상품이 존재하지 않습니다."
  - "상품의 수량이 부족합니다"
  - "현재 너무 많은 요청을 처리하고 있습니다. 다시 시도해주세요 (락)"

logging:
  level:
    org.hibernate.sql: TRACE
#
#    org.springframework.kafka: TRACE
#    org.apache.kafka: TRACE