server.port: 8081

spring:
  application:
    name: foods

  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/software/h2/h2-datafile/kafka
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true

orders:
  events:
    topic:
      name: orders.order-created-event

foods:
  events:
    topic:
      name: foods.order-created-event
      fail: foods.foods-reservation-fail-event

payment:
  events:
    topic:
      name: payments.payment-process-command

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3

logging:
  level:
    org.hibernate.sql: TRACE

#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG