server.port: 0

spring:
  application:
    name: payments

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: payments-tx

    consumer:
      group-id: payments

payments:
  events:
    topic:
      name: payments.order-created-event
      fail: payments.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3