server.port: 0

spring:
  application:
    name: payments

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      enable:
        idempotence: true

    consumer:
      bootstrap-servers: localhost:9092
      group-id: payments
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.f-lab.joyeuse_planete.core.*

payments:
  events:
    topic:
      name: payments.order-created-event
      fail: payments.order-creation-failed-event

kafka:
  topic:
    partitions: 3

  container:
    concurrency: 3