name: Java CI with Gradle
on:
  [ push, pull_request ]

jobs:
  build_on_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test and Build
        run: |
          chmod +x gradlew
          ./gradlew clean build



